[settings]
experimental = true
env_shell_expand = true

[env]
YK_GPG_KEY_TYPE = "ed25519"
YK_GPG_EXPIRATION = "2y"
YK_GPG_IDENTITY = ""
YK_GPG_TOR_PROXY = ""
YK_GPG_CONFIG_DIR = "${XDG_CONFIG_HOME:-$HOME/.config}/yk-gpg"
YK_GPG_DATA_DIR = "${XDG_DATA_HOME:-$HOME/.local/share}/yk-gpg"
YK_GPG_STATE_DIR = "${XDG_STATE_HOME:-$HOME/.local/state}/yk-gpg"
