name: Unit Tests
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install bash bats-core gnupg jq
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y bats gnupg jq
      - run: bats test/unit/
        env:
          TERM: xterm
          CI: true
